sg_db/crossing/urls.py
from django.urls import path

from . import views


app_name = "crossing"
urlpatterns = [
        path("", views.crossesView, name = "crosses_view"),
        path("crossesTable", views.crossesWrapperView, name = "crosses_wrapper_view"),
        path("crossesTable/tableContent", views.crossesTableView, name = "crosses_table_view"),
        path("entries", views.wcpView, name = "Entries View"),
        path("entries/entriesTable", views.wcpWrapperView, name = "entries_wrapper_view"),
        path("entries/entriesTable/tableContent", views.wcpTableView, name = "entries_table_view"),
        path("families", views.familiesView, name = "families_view"),
        path("families/familiesTable", views.familiesWrapperView, name = "families_wrapper_view"),
        path("families/familiesTable/tableContent", views.familiesTableView, name = "families_table_view"),
        path("<str:id_str>/", views.entryDetail, name = "entry_detail"),
        path("<str:id_str>/edit/", views.entryEditForm, name = "entry_edit_form"),
        ]

sg_db/sg_db/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="sg_db/index_info.html"), name = "index_info"), #Allows loading template directly without views file
    path("crossing_shiny", TemplateView.as_view(template_name="sg_db/crossing_shiny.html"), name = "crossing_shiny"), 
    path("crossesmade_shiny", TemplateView.as_view(template_name="sg_db/crossesmade_shiny.html"), name = "crossesmade_shiny"), 
    path('crossing/', include("crossing.urls")),
    path('tools/', include("tools.urls")),
    path('germplasm/', include("germplasm.urls")),
    path('admin/', admin.site.urls),
]

sg_db/crossing/forms.py
from django.forms import IntegerField, FileField, Form, ModelForm, NumberInput

from .models import WCP_Entries, Crosses, Families


class WCPEntryForm(ModelForm):
    class Meta:
        model = WCP_Entries
        fields = ["wcp_id", "year_text", "eno_int", "desig_text", "purdy_text",
                  "cp_group_text", "source_text", "genes_text", "notes_text", "sample_id_text"]

class UploadWCPForm(Form):
    WCP_Entries_File = FileField(label = '')
    WCP_Entries_File.widget.attrs.update({'class': 'file-upload'})

class CrossesEntryForm(ModelForm):
    class Meta:
        model = Crosses 
        fields = ["cross_id", "year_text", "parent_one", "parent_two", "cross_date", 
                  "crosser_text", "status_text", "seed_int"]

class CrossesUpdateStatusForm(ModelForm):
    class Meta:
        model = Crosses 
        fields = ["status_text", "seed_int"]

class UploadCrossesForm(Form):
    Crosses_File = FileField(label = '')
    Crosses_File.widget.attrs.update({'class': 'file-upload'})

class FamiliesEntryForm(ModelForm):
    class Meta:
        model = Families 
        fields = ["family_id", "purdy_text", "genes_text", "notes_text", 'cross']

class UploadFamilyForm(Form):
    Families_File = FileField(label = '')
    Families_File.widget.attrs.update({'class': 'file-upload'})

sg_db/crossing/views.py
import django_tables2 as tables
import re
import sys
import csv

from datetime import date, datetime
from io import TextIOWrapper
from functools import reduce

from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse, QueryDict, HttpResponseNotFound
from django.template import loader, RequestContext
from django.db.models import Q

from germplasm.models import Trials
from germplasm.forms import TrialEntryForm

from .models import WCP_Entries, Crosses, Families
from .tables import wcpTable, crossesTable, familiesTable
from .forms import WCPEntryForm, UploadWCPForm, CrossesEntryForm, CrossesUpdateStatusForm, UploadCrossesForm, FamiliesEntryForm, UploadFamilyForm
from tools.forms import TimesToPrintForm

from django.views.generic.base import View

def wcpView(request):
    return render(request, "crossing/wcp_index.html")

def wcpWrapperView(request):
    if request.method == 'GET':
        return render(request, "crossing/wcp_table_wrapper.html", {'upload_form': UploadWCPForm()})
    elif request.method == 'POST':
        WCP_Entries_File = request.FILES["WCP_Entries_File"]
        rows = TextIOWrapper(WCP_Entries_File, encoding="utf-8", newline="")
        for row in csv.DictReader(rows):
            form = WCPEntryForm(row)
            if form.is_valid():
                form.save()
            else: 
                print(form.errors)

        return render(request, "crossing/wcp_index.html")

def wcpTableView(request):
    cur_year = request.GET['years']

    if 'filter' in request.GET.keys():
        query_str = request.GET['filter']
        table = wcpTable(WCP_Entries.objects.filter(
            Q(year_text__icontains=cur_year),
            Q(wcp_id__icontains=query_str) | 
            Q(desig_text__icontains=query_str) |
            Q(purdy_text__icontains=query_str) |
            Q(genes_text__icontains=query_str) |
            Q(notes_text__icontains=query_str)))
    else:
        table = wcpTable(WCP_Entries.objects.filter(Q(year_text__icontains=cur_year)))

    tables.config.RequestConfig(request, paginate={"per_page": 15}).configure(table)
    return render(request, 'crossing/display_table.html', {"table" : table}) 

def crossesView(request):
    return render(request, "crossing/crosses_index.html")

def crossesWrapperView(request):
    print(request.method, file = sys.stderr)
    if request.method == 'GET':
        return render(request, "crossing/crosses_table_wrapper.html", {"form": UploadCrossesForm()})
    elif request.method == 'POST':
        Crosses_File = request.FILES["Crosses_File"]
        rows = TextIOWrapper(Crosses_File, encoding="utf-8", newline="")
        print("Test:")
        for row in reversed(list(csv.DictReader(rows))):
            print("Hello")
            print(row)
            print(row['crossDbId'])
            #Should this chunk here be moved to the model.save() function?

            #99 used as code for failure
            if int(row['seeds']) == 0:
                rowStatus = "Made"
            elif int(row['seeds']) == 99:
                row['seeds'] = 0
                rowStatus = "Failed"
            elif int(row['seeds']) > 0:
                rowStatus = "Set"


            #If the row already exists, update with new data. 
            if Crosses.objects.filter(cross_id = row['crossDbId']).exists():
                existing_cross = Crosses.objects.get(cross_id = row['crossDbId'])
                #In this case, the *only* thing we want to update is the seed and status.
                modStatus = {'status_text' : rowStatus,
                             'seed_int' : int(row['seeds'])}

                form = CrossesUpdateStatusForm(modStatus, instance = existing_cross)
                form.save()

            else:
                date_formats = ("%Y-%m-%d_%H_%M_%S_%f", "%Y-%m-%d", "%m/%d/%Y",  "%m/%d/%y", "%m-%d-%Y", )

                format_i = 0
                crossTime = None
                while format_i <= len(date_formats):
                    try:
                        crossTime =  datetime.strptime(row['timestamp'], date_formats[format_i])
                        format_i = 100
                    except:
                        format_i += 1

                if crossTime == None:
                    print("No suitable formats match datetime string:")
                    print("|"+row['timestamp']+"|")
                    break

                #Get year from parent one ID
                curYear = "20" + re.search("(\d{2})_", row['femaleObsUnitDbId']).group(1)

                #Create new dictionary based on dictionary defined by InterCross column names
                modRow = {'cross_id' : row['crossDbId'],
                          'year_text' : curYear,
                          'parent_one' : row['femaleObsUnitDbId'], 
                          'parent_two' : row['maleObsUnitDbId'], 
                          'cross_date' : crossTime, 
                          'crosser_text' : row['person'],
                          'status_text' : rowStatus,
                          'seed_int' : int(row['seeds'])}

                form = CrossesEntryForm(modRow)

                if form.is_valid():
                    form.save()
                else:
                    print(form.errors)
        return render(request, "crossing/crosses_table_wrapper.html", {"form": UploadCrossesForm()})

def crossesTableView(request):
    cur_year = request.GET['years']

    if 'filter' in request.GET.keys():
        query_str = request.GET['filter']
        table = crossesTable(Crosses.objects.filter(
            Q(year_text__icontains=cur_year),
            Q(cross_id__icontains=query_str) | 
            Q(parent_one__desig_text__icontains=query_str) |
            Q(parent_two__desig_text__icontains=query_str) |
            Q(crosser_text__icontains=query_str) |
            Q(status_text__icontains=query_str)))
    else:
        table = crossesTable(Crosses.objects.filter(Q(year_text__icontains=cur_year)))

    table.order_by = "cross_id"
    tables.config.RequestConfig(request, paginate={"per_page": 15}).configure(table)
    return render(request, 'crossing/display_table.html', {"table" : table}) 

def familiesView(request):
    return render(request, "crossing/families_index.html")

def familiesWrapperView(request):
    if request.method == 'GET':
        return render(request, "crossing/families_table_wrapper.html", {'upload_form': UploadFamilyForm()})
    elif request.method == 'POST':
        Families_File = request.FILES["Families_File"]
        rows = TextIOWrapper(Families_File, encoding="utf-8", newline="")
        for row in csv.DictReader(rows):
            form = FamiliesEntryForm(row)
            if form.is_valid():
                form.save()
            else: 
                print(form.errors)
                print("Error with family: " + row['family_id'] + " and cross: " + row['cross'])

        return render(request, "crossing/wcp_index.html")

def familiesTableView(request):
    cur_year = request.GET['years']

    if 'filter' in request.GET.keys():
        query_str = request.GET['filter']
        table = familiesTable(Families.objects.filter(
            Q(year_text__icontains=cur_year),
            Q(family_id__icontains=query_str) | 
            Q(purdy_text__icontains=query_str) |
            Q(cross__cross_id__icontains=query_str) |
            Q(genes_text__icontains=query_str)))
    else:
        table = familiesTable(Families.objects.filter(Q(year_text__icontains=cur_year)))
    tables.config.RequestConfig(request, paginate={"per_page": 15}).configure(table)
    return render(request, 'crossing/display_table.html', {"table" : table}) 


def entryDetail(request, id_str):
    if re.match(r'^WCP', id_str):
        curModel = WCP_Entries
        curForm = WCPEntryForm
        htmlPath = "crossing/entryDetail.html"
    elif re.match(r'^T', id_str):
        curModel = Crosses
        curForm = CrossesEntryForm
        htmlPath = "crossing/crossDetail.html"
    elif re.match(r'^LA', id_str):
        curModel = Families 
        curForm = FamiliesEntryForm
        htmlPath = "crossing/familyDetail.html"
    elif re.match(r'^\w{3}\d{2}', id_str):
        curModel = Trials
        curForm = TrialEntryForm
        htmlPath = "germplasm/trialDetail.html"
    else:
        print(id_str)
        return HttpResponseNotFound(id_str)

    entry = get_object_or_404(curModel, pk = id_str)

    if request.method == 'GET':
        return render(request, htmlPath, {"entry": entry})
    elif request.method == 'PUT':
        print(id_str, file = sys.stderr)
        data = QueryDict(request.body).dict()
        form = curForm(data, instance = entry)
        if form.is_valid():
            form.save()
        else:
            print(form.errors, file=sys.stderr)

        return render(request, htmlPath, {"entry": entry})

def entryEditForm(request, id_str):
    if re.match(r'^WCP', id_str):
        curModel = WCP_Entries
        curForm = WCPEntryForm
    elif re.match(r'^T', id_str):
        curModel = Crosses
        curForm = CrossesEntryForm
    elif re.match(r'^LA', id_str):
        curModel = Families
        curForm = FamiliesEntryForm
    elif re.match(r'^\w{3}\d{2}', id_str):
        curModel = Trials
        curForm = TrialEntryForm
    else:
        print(id_str)
        return HttpResponseNotFound(id_str)

    entry = get_object_or_404(curModel, pk = id_str)
    form = curForm(instance = entry)
    return render(request, "crossing/entryEdit.html", {"entry": entry, "form": form})

sg_db/crossing/templates/crossing/crossDetail.html
<div class="table-tools-wrapper">
  <div class="entry-title">
	<h3> <span> {{ entry.cross_id }} </span></h3>
  </div>
  <div class="row">
    <div class="column">
       <div class="detail-box">
	<h3> Status </h3>
	<p class="detail_info"> {{entry.status_text}} </p>
       </div>
       <div class="detail-box">
	<h3> Crosser </h3>
	<p class="detail_info"> {{ entry.crosser_text }} </p> 
       </div>
    </div>
    <div class="column">
       <div class="detail-box">
	<h3> Seed </h3>
	<p class="detail_info"> {{entry.seed_int}} </p>
       </div>
       <div class="detail-box">
	<h3> Cross Date </h3>
	<p class="detail_info"> {{ entry.cross_date }} </p> 
       </div>
    </div>
  </div>
  <div class="row">
    <div class="column">
       <div class="entry-title">
	       <h3> <span> &#9792; {{  entry.parent_one }} </span></h3>
       </div>
       <div class="detail-box">
        <h3> Pedigree </h3>
        <p class="detail_info">{{ entry.parent_one.purdy_text }}</p>
       </div>
       <div class="detail-box">
        <h3> WCP Year and Group </h3>
        <p class="detail_info">{{ entry.parent_one.wcp_id }} - {{ entry.parent_one.cp_group_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Genes </h3>
        <p class="detail_info">{{ entry.parent_one.genes_text }}</p>
       </div>
        <div class="detail-box">
        <h3> Notes </h3>
       <p class="detail_info">{{ entry.parent_one.notes_text }}</p>
       </div>
        <div class="detail-box">
        <h3> Genotype Sample Id </h3>
       <p class="detail_info">{{ entry.parent_one.sample_id_text }}</p>
       </div>
    </div>
    <div class="column">
       <div class="entry-title">
	       <h3> <span> &#9794; {{ entry.parent_two }} </span></h3>
       </div>
       <div class="detail-box">
       	<h3> Pedigree </h3>
       	<p class="detail_info">{{ entry.parent_two.purdy_text }}</p>
       </div>
       <div class="detail-box">
        <h3> WCP Year and Group </h3>
        <p class="detail_info">{{ entry.parent_two.wcp_id }} - {{ entry.parent_two.cp_group_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Genes </h3>
        <p class="detail_info">{{ entry.parent_two.genes_text }}
       </div>
       <div class="detail-box">
        <h3> Notes </h3>
        <p class="detail_info">{{ entry.parent_two.notes_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Genotype Sample Id </h3>
        <p class="detail_info">{{ entry.parent_two.sample_id_text }}</p>
       </div>
    </div>
  </div>
	
	<button hx-get="{% url 'crossing:crosses_wrapper_view' %}"
		hx-target="div.table-tools-wrapper"
		hx-swap="outerHTML">Return</button>

	<button hx-get="{% url 'crossing:entry_edit_form' entry.pk  %}"
		hx-target="div.table-tools-wrapper"
		> Edit </button>
</div>

sg_db/crossing/templates/crossing/crosses_index.html
{% extends "base.html" %}

{% load django_tables2 %}
{% load static %}

{% block extrastyles %}
	<title> Crosses Made </title>
        <link rel="stylesheet" href={% static 'sg_db/css/table_style.css' %}>
{% endblock %}

{% block main %}

<main>
    <h2> Current Crosses </h2>

    <div hx-get="{% url 'crossing:crosses_wrapper_view' %}"
	 hx-trigger="load"
	 hx-swap="outerHTML">
	    Error loading table wrapper!
    </div>

</main>

{% endblock %}

sg_db/crossing/templates/crossing/crosses_table_wrapper.html
<div class="table-tools-wrapper">

	<label for = "filter-box"
	       class = "filter-box"> Search table: </label>
	<input type = "search"
	       class = "filter-box"
	       name = "filter"
	       id = "filter-box"
	       placeholder = "Filter..."
	       hx-get="{% url 'crossing:crosses_table_view' %}"
	       hx-trigger="keyup delay:500ms, changed, search"
	       hx-target="div.table-container"
	       hx-swap="outerHTML"
               hx-include="[name='years']">

        <select id="years" name="years" class = "select-options-box"
               hx-get="{% url 'crossing:crosses_table_view' %}"
               hx-trigger="click"
               hx-target="div.table-container"
               hx-swap="outerHTML"
               hx-include="[name='filter']">
                <option value = "2025">2025</option>
                <option value = "2024">2024</option>
                <option value = "2023">2023</option>
                <option value = "2022">2022</option>
                <option value = "2021">2021</option>
                <option value = "2020">2020</option>
                <option value = "2019">2019</option>
                <option value = "20">All</option>
        </select>


	<div class = "styled-link" >
		<a href="/crossesmade_shiny" target="_blank" >  View graph of current two-way crosses  </a> 
	</div>

	<div hx-get="{% url 'crossing:crosses_table_view' %}" hx-trigger="load" hx-swap="outerHTML" hx-include="[name='years']">
		Error loading table!
	</div>

	<form style="display: inline"
	      action="/tools/export/csv/Crosses" 
	      method = "get">
		<button> Download CSV </button>
	</form>

	<form hx-post = "{% url 'crossing:crosses_wrapper_view' %}"
	      hx-encoding = "multipart/form-data"
	      hx-target="div.table-tools-wrapper">
		{% csrf_token %}
		{{ form }}
		<input class = "button" type="submit" value = "Submit">
	</form>
</div>

sg_db/crossing/templates/crossing/detail.html
{% extends "base.html" %} 

{% block main %}

<main>

<h2> Cross Detail </h2>

{% block crosses %}

<h3> {{ cross.cross_text }} </h3>

<u1> Parents: {{ cross.parent_one }} / {{ cross.parent_two }} </u1> <br / >
<u1> Crosser: {{ cross.crosser_text }} </u1>

</main>

{% endblock %}

{% endblock %}

sg_db/crossing/templates/crossing/entryDetail.html
<div class="table-tools-wrapper">
  <div class="entry-title">
	<h3> <span> {{ entry.wcp_id }} : {{ entry.desig_text }}</span></h3>
  </div>
  <div class="row">
    <div class="column">
      <div class="detail-box">
	<h3> Year: </h3>
	<p class="detail_info"> {{entry.year_text}} crossing block.</p>
      </div>
      <div class="detail-box">
	<h3> Entry Number </h3>
	<p class="detail_info"> Number {{entry.eno_text}} </p>
      </div>
      <div class="detail-box">
	<h3> Desig </h3>
	<p class="detail_info"> {{entry.desig_text}} </p>
      </div>
      <div class="detail-box">
	<h3> Pedigree </h3>
	<p class="detail_info"> {{ entry.purdy_text }} </p> 
      </div>
    </div>
    <div class="column">
      <div class="detail-box">
	<h3> Genotyping Id </h3>
	<p class="detail_info"> {{entry.sample_id_text}} </p>
      </div>
      <div class="detail-box">
	<h3> CP Group </h3>
	<p class="detail_info"> {{entry.cp_group_text}} </p>
      </div>
      <div class="detail-box">
	<h3> Genes </h3>
	<p class="detail_info"> {{entry.genes_text}} </p>
      </div>
      <div class="detail-box">
	<h3> Notes </h3>
	<p class="detail_info"> {{entry.notes_text}} </p>
      </div>
    </div>
  </div>
	<br / >
	
	<button hx-get="{% url 'crossing:entries_wrapper_view' %}"
		hx-target="div.table-tools-wrapper"
		hx-swap="outerHTML">Return</button>

	<button hx-get="{% url 'crossing:entry_edit_form' entry.pk  %}"
		hx-target="div.table-tools-wrapper"
		> Edit </button>
</div>

sg_db/crossing/templates/crossing/entryEdit.html
<div class="table-tools-wrapper">

    <div class="entry-title">
	 {% if  entry.desig_text is None  %}
	    <h3> <span> {{ entry.pk }} </span> </h3>
	 {% else %}
	    <h3> <span> {{ entry.pk }} : {{ entry.desig_text }} </span> </h3>
	 {% endif %}
    </div>

    <form hx-put="{% url 'crossing:entry_detail' entry.pk %}"
	  hx-target="div.table-tools-wrapper">
      {% csrf_token %}

      <div class = "row">
	<div class = "column">
	{% for field in form %}
	{# Need to change this so half of form length #}
	  {% if forloop.counter0 == 5 %}
	    </div>
	    <div class = "column">
	  {% endif %}

	  <h3 class="detail_header"> {{field.label_tag}} </h3>
	  <p class="detail_info"> {{ field }} </p>
	{% endfor %}
	</div>
      </div>

      <input class = "button" type="submit" value = "Save" />
</form>
	<button hx-get="{% url 'crossing:entry_detail' entry.pk %}"
		hx-target="div.table-tools-wrapper"
		hx-swap="outerHTML">Return</button>
</div>

sg_db/crossing/templates/crossing/families_index.html
{% extends "base.html" %}

{% load django_tables2 %}
{% load static %}

{% block extrastyles %}
	<title> Wheat Families </title>
        <link rel="stylesheet" href={% static 'sg_db/css/table_style.css' %}>
{% endblock %}

{% block main %}

<main>
    <h2> Families </h2>

    <div hx-get="{% url 'crossing:families_wrapper_view' %}"
	 hx-trigger="load"
	 hx-swap="outerHTML">
	    Error loading table wrapper!
    </div>

</main>

{% endblock %}

sg_db/crossing/templates/crossing/families_table_wrapper.html
<div class="table-tools-wrapper">

	<label for = "filter-box"
	       class = "filter-box"> Search table: </label>
	<input type = "search"
	       class = "filter-box"
	       name = "filter"
	       id = "filter-box"
	       placeholder = "Filter..."
	       hx-get="{% url 'crossing:families_table_view' %}"
	       hx-trigger="keyup delay:500ms, changed, search"
	       hx-target="div.table-container"
	       hx-swap="outerHTML"
               hx-include="[name='years']">

        <select id="years" name="years" class = "select-options-box"
               hx-get="{% url 'crossing:families_table_view' %}"
               hx-trigger="click"
               hx-target="div.table-container"
               hx-swap="outerHTML"
               hx-include="[name='filter']">
                <option value = "2025">2025</option>
                <option value = "2024">2024</option>
                <option value = "2023">2023</option>
                <option value = "2022">2022</option>
                <option value = "2021">2021</option>
                <option value = "2020">2020</option>
                <option value = "2019">2019</option>
                <option value = "20">All</option>
        </select>


	<div hx-get="{% url 'crossing:families_table_view' %}" hx-trigger="load" hx-swap="outerHTML" hx-include="[name='years']">
		Error loading table!
	</div>

	<form style="display: inline"
	      action="/tools/export/csv/Families" 
	      method = "get">
		<button> Download CSV </button>
	</form>

	<form action="/crossing/families/familiesTable"
              enctype="multipart/form-data"
              method="post">
              {% csrf_token %}
              {{ upload_form }}
                      <input type = "submit"
                     class = 'button'
                     name = 'upload_files'
                     value = "Upload">
        </form>


</div>

sg_db/crossing/templates/crossing/familyDetail.html
<div class="table-tools-wrapper">
  <div class="entry-title">
	<h3> <span> {{ entry.family_id }} </span></h3>
  </div>
  <div class="row">
    <div class="column">
	<div class="detail-box">
	 <h3> Purdy Pedigree </h3>
	 <p class="detail_info"> {{ entry.purdy_text }} </p>
        </div>
	 <div class="detail-box">
	 <h3> Segregating Genes </h3>
	<p class="detail_info"> {{ entry.genes_text }} </p> 
        </div>
    </div>
    <div class="column">
	<div class="detail-box">
	 <h3> Cross Info </h3>
	 <p class="detail_info"> {{ entry.cross }} - {{ entry.cross.crosser_text }} - {{ entry.cross.cross_date }} </p>
        </div>
	 <div class="detail-box">
	 <h3> Notes </h3>
	<p class="detail_info"> {{ entry.notes_text }} </p> 
        </div>
    </div>
  </div>
  <div class="row">
    <div class="column">
       <div class="entry-title">
	       <h3> <span> &#9792; {{ entry.cross.parent_one }} </a> </span></h3>
       </div>
       <div class="detail-box">
        <h3> Pedigree </h3>
	<p class="detail_info">{{ entry.cross.parent_one.purdy_text }}</p>
       </div>
       <div class="detail-box">
        <h3> WCP Year and Group </h3>
        <p class="detail_info">{{ entry.cross.parent_one.wcp_id }} - {{ entry.cross.parent_one.cp_group_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Genes </h3>
        <p class="detail_info">{{ entry.cross.parent_one.genes_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Notes </h3>
        <p class="detail_info">{{ entry.cross.parent_one.notes_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Genotype Sample Id </h3>
        <p class="detail_info">{{ entry.cross.parent_one.sample_id_text }}</p>
       </div>
    </div>
    <div class="column">
       <div class="entry-title">
	<h3> <span> &#9794; {{ entry.cross.parent_two }} </span></h3>
       </div>
       <div class="detail-box">
        <h3> Pedigree </h3>
        <p class="detail_info">{{ entry.cross.parent_two.purdy_text }}</p>
       </div>
       <div class="detail-box">
        <h3> WCP Year and Group </h3>
        <p class="detail_info">{{ entry.cross.parent_two.wcp_id }} - {{ entry.cross.parent_two.cp_group_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Genes </h3>
        <p class="detail_info">{{ entry.cross.parent_two.genes_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Notes </h3>
        <p class="detail_info">{{ entry.cross.parent_two.notes_text }}</p>
       </div>
       <div class="detail-box">
        <h3> Genotype Sample Id </h3>
        <p class="detail_info">{{ entry.cross.parent_two.sample_id_text }}</p>
       </div>
    </div>
  </div>	
	<button hx-get="{% url 'crossing:families_wrapper_view' %}"
		hx-target="div.table-tools-wrapper"
		hx-swap="outerHTML">Return</button>

	<button hx-get="{% url 'crossing:entry_edit_form' entry.pk  %}"
		hx-target="div.table-tools-wrapper"
		> Edit </button>
</div>

sg_db/crossing/templates/crossing/labels.html
<!DOCTYPE html>
{% extends "base.html" %}  

{% block main %} 


<main>
	<h2> Generate Labels </h2>

	<form 
	    action="/crossing/labels"
	    enctype="multipart/form-data"
	    method="post"
	>
	    {% csrf_token %}
	    
	    {% for field in label_form %} 

		<h3 class="detail_header"> {{field.label_tag}} </h3>
		<p class="detail_info"> {{ field }} </p>

	    {% endfor %}
	    <input type="submit" 
		   class='button'
	           name = 'upload_files' 
		   value = "Submit">
	</form>
</main>

{% endblock %} 

sg_db/crossing/templates/crossing/wcp_index.html
{% extends "base.html" %}  

{% load django_tables2 %}
{% load static %}

{% block extrastyles %}
	<title> Wheat crossing block </title>
	<link rel="stylesheet" href={% static 'sg_db/css/table_style.css' %}>
{% endblock %}

{% block main %} 

<main>

	<h2> Crossing Block Entries </h2>

	<div hx-get="{% url 'crossing:entries_wrapper_view' %}"
	     hx-trigger="load"
	     hx-swap="outerHTML">
		Error loading table wrapper!
	</div>

</main>

{% endblock %} 