sg_db/crossing/urls.py
from django.urls import path

from . import views


app_name = "crossing"
urlpatterns = [
        path("", views.crossesView, name = "crosses_view"),
        path("crossesTable", views.crossesWrapperView, name = "crosses_wrapper_view"),
        path("crossesTable/tableContent", views.crossesTableView, name = "crosses_table_view"),
        path("entries", views.wcpView, name = "Entries View"),
        path("entries/entriesTable", views.wcpWrapperView, name = "entries_wrapper_view"),
        path("entries/entriesTable/tableContent", views.wcpTableView, name = "entries_table_view"),
        path("families", views.familiesView, name = "families_view"),
        path("families/familiesTable", views.familiesWrapperView, name = "families_wrapper_view"),
        path("families/familiesTable/tableContent", views.familiesTableView, name = "families_table_view"),
        path("<str:id_str>/", views.entryDetail, name = "entry_detail"),
        path("<str:id_str>/edit/", views.entryEditForm, name = "entry_edit_form"),
        ]

sg_db/germplasm/urls.py
from django.urls import path

from . import views

app_name = "germplasm"
urlpatterns = [
        path("", views.plotView, name = "plots_view"),
        path("plotsUpload", views.plotUploadView, name = "plots_manual_upload"),
        path("plotsTable", views.plotWrapperView, name = "plots_wrapper_view"),
        path("plotsTable/tableContent", views.plotTableView, name = "plots_table_view"),
        path("stocks", views.stockView, name = "stocks_view"),
        path("stocks/stocksTable", views.stockWrapperView, name = "stocks_wrapper_view"),
        path("stocks/stocksTable/tableContent", views.stockTableView, name = "stocks_table_view"),
        path("stocks/genNursery", views.newNurseryView, name = "new_nursery_view"),
        path("stocks/genNursery/forms", views.newNurseryFormsView, name = "new_nursery_forms_view"),
        path("stocks/genNursery/details", views.newNurseryDetailsView, name = "new_nursery_details"),
        path("stocks/genNursery/plotTable", views.newNurseryPlotsTableView, name = "new_nursery_plots_table"),
        path("stocks/genNursery/forms/checkForms", views.checkFormsView, name = "check_forms"),
        path("trials", views.trialView, name = "trials_view"),
        path("trials/trialsUpload", views.trialUploadView, name = "trials_manual_upload"),
        path("trials/trialsTable", views.trialWrapperView, name = "trials_wrapper_view"),
        path("trials/trialsTable/tableContent", views.trialTableView, name = "trials_table_view"),
        path("predictions", views.predictionsView, name = "predictions_view"),
        path("predictions/predictionsUpload", views.predictionsUploadView, name = "predictions_manual_upload"),
        path("predictions/predictionsTable", views.predictionsWrapperView, name = "predictions_wrapper_view"),
        path("predictions/predictionsTable/predictionsContent", views.predictionsTableView, name = "predictions_table_view"),
        path("predictions/predictionsTable/predictionsContent/<str:trial_filter>", views.predictionsTableView, name = "predictions_table_view"),

        ]

sg_db/sg_db/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="sg_db/index_info.html"), name = "index_info"), #Allows loading template directly without views file
    path("crossing_shiny", TemplateView.as_view(template_name="sg_db/crossing_shiny.html"), name = "crossing_shiny"), 
    path("crossesmade_shiny", TemplateView.as_view(template_name="sg_db/crossesmade_shiny.html"), name = "crossesmade_shiny"), 
    path('crossing/', include("crossing.urls")),
    path('tools/', include("tools.urls")),
    path('germplasm/', include("germplasm.urls")),
    path('admin/', admin.site.urls),
]

sg_db/tools/urls.py
from django.urls import path

from . import views


app_name = "tools"
urlpatterns = [
       # path("", #Index view maybe?
       path('labels', views.lblView, name = "labels_view"),
       path('labels/display', views.labelDisplayView, name = "display_label_view"),
       path('fieldbooks', views.fieldbookView, name = "fieldbooks_view"),
       path('fieldbooks/<str:file_str>', views.renderFieldbookView, name = 'render_fieldbook_view'),
       path('export/csv/<str:requested_model>', views.export_csv, name='export_csv'),
       path('export/csv/<str:requested_model>/<str:filter_str>', views.export_csv, name='export_csv'),
       path('export/htmx', views.htmx_csv_view, name = "htmx_csv_view"),
       #path('export/lbl/<str:requested_model>', views.export_labels, name='export_labels'),
       ]

sg_db/germplasm/forms.py
from django.forms import Form, ModelForm, FileField

from .models import Stocks, Plots, Trials, Predictions

class PlotEntryForm(ModelForm):
    class Meta:
        model = Plots
        exclude = []

class StockEntryForm(ModelForm):
    class Meta:
        model = Stocks
        exclude = []

class StockUpdateAmountForm(ModelForm):
    class Meta:
        model = Stocks
        fields = ["amount_decimal"]

class TrialEntryForm(ModelForm):
    class Meta:
        model = Trials
        fields = ["trial_id", "year_text", "location_text", "plot_type", "planting_date", "harvest_date", "status_text"]
        exclude = []

class PredictionsEntryForm(ModelForm):
    class Meta:
        model = Predictions
        exclude = []

class UploadStocksForm(Form):
    Stocks_File = FileField(label = '')
    Stocks_File.widget.attrs.update({'class': 'file-upload'})

class UploadPlotsForm(Form):
    Plots_File = FileField(label = '')
    Plots_File.widget.attrs.update({'class': 'file-upload'})
    
class UploadTrialsForm(Form):
    Trials_File = FileField(label = '')
    Trials_File.widget.attrs.update({'class': 'file-upload'})

class UploadPredictionsForm(Form):
    Predictions_File = FileField(label = '')
    Predictions_File.widget.attrs.update({'class': 'file-upload'})

sg_db/germplasm/views.py
import csv
import re

import decimal
import pandas as pd
from datetime import date, datetime
from io import TextIOWrapper

import django_tables2 as tables

from django.shortcuts import render
from django.db.models import Q
from django.db import connection

from .models import Trials, Stocks, Plots, Predictions
from crossing.models import Families
from .forms import UploadStocksForm, TrialEntryForm, PlotEntryForm, StockEntryForm, PredictionsEntryForm, UploadPlotsForm, UploadTrialsForm, StockUpdateAmountForm, UploadPredictionsForm
from .tables import stockTable, plotTable, trialTable, predictionTable


def stockView(request):
    return render(request, "germplasm/stocks_index.html")

def stockWrapperView(request):
    if request.method == 'GET':
        return render(request, "germplasm/stocks_table_wrapper.html", {'upload_form': UploadStocksForm()})
    elif request.method == 'POST':
        Stocks_File = request.FILES["Stocks_File"]
        if 'Stocks_File' in request.FILES:
            #Sd units upload different than sd units for filtering
            stock_units = request.POST["sd_units_upload"] 

            Stocks_File = request.FILES["Stocks_File"]
            rows = TextIOWrapper(Stocks_File, encoding="utf-8", newline="")

            #This loop will ingest the CSV, do some cleaning, and output Dict
            #Use .reader instead of dictreader because use column position instead
            #All inputs should have stock id in left, amounts in right. header optional.

            new_stocks_dict = {}
            
            for row in csv.reader(rows):
                try: 
                    #Skip the header and avoid extraneous stuff in the file
                    stock_amount = float(row[1])

                    plot_bag_name = row[0]
                    plot_bag_name = plot_bag_name.upper()

                    #Because the barcodes are smaller, print without underscore
                    plot_bag_name = plot_bag_name.replace(" ", "_")

                    #Check padding with 0's 
                    if plot_bag_name[1:3] == "HR":
                        sep_index = plot_bag_name.find("_") + 1
                        row_str = plot_bag_name[sep_index:len(plot_bag_name)]

                        if len(row_str) < 4:
                            row_str = row_str.rjust(5, "0")
                            plot_bag_name = plot_bag_name[0:sep_index] + row_str

                    if Plots.objects.filter(plot_id = plot_bag_name).exists():
                        new_stocks_dict[plot_bag_name] = stock_amount
                        print(new_stocks_dict[plot_bag_name])

                    else:
                        print("ERROR: Plot ID not in DB")
                        break

                except:
                    pass

            #Check length of dict is N or N-1 of file?
            print(new_stocks_dict)
            for stock_plot_name in new_stocks_dict.keys():
                stock_amount = new_stocks_dict[stock_plot_name]

                stock_plot = Plots.objects.get(plot_id = stock_plot_name)
               
                print(stock_plot)
                print(stock_plot.family)

                if stock_units == "hds":
                    new_gen_derived = stock_plot.gen_inbred_int

                else:
                    new_gen_derived = stock_plot.gen_derived_int

                new_gen_inbred = stock_plot.gen_inbred_int + 1

                new_stock_id = "S-" + str(stock_plot.plot_id)

                new_stock = {
                        "stock_id" : new_stock_id,
                        "source_plot" : stock_plot,
                        "family" : stock_plot.family,
                        "gen_derived_int" : new_gen_derived,
                        "gen_inbred_int" : new_gen_inbred,
                        "location_text" : "",
                        "amount_decimal" : stock_amount,
                        "amount_units" : stock_units,
                        "entry_fixed" : True
                }

                form = StockEntryForm(new_stock)

                if form.is_valid():
                    form.save()
                else:
                    print(form.errors)

            return render(request, "germplasm/stocks_table_wrapper.html", {'upload_form': UploadStocksForm()})
 
def stockTableView(request, page_number = 15):
    table = filterStockTable(request)

    if "first_n" in request.GET.keys():
        if request.GET["first_n"] != "":
            page_number = int(request.GET['first_n'])

    tables.config.RequestConfig(request, paginate={"per_page": page_number}).configure(table)
    return render(request, 'crossing/display_table.html', {"table" : table})


#Will generalize and move to other stocks
def filterStockTable(request, return_table = True):
    filter_object = Stocks.objects.filter()

    if request.method == 'GET':
        requestDict = request.GET

    elif request.method == 'POST':
        requestDict = request.POST

    #This can for sure be a for loop,
    print(requestDict)
    #Progressively add filters based on parameters
    for filter_var in requestDict.keys():
        if requestDict[filter_var] != "":
            if filter_var == "filter":
                filter_object = filter_object.filter(Q(stock_id__icontains=requestDict[filter_var]) | Q(family__family_id__icontains=requestDict[filter_var]))

            elif filter_var == "gens":
                query_int = int(re.sub("F", "", requestDict[filter_var]))
                filter_object = filter_object.filter(gen_inbred_int = query_int)

            elif filter_var == "sd_units":
                print(requestDict[filter_var])
                filter_object = filter_object.filter(amount_units = requestDict[filter_var])

    print(filter_object)

    #This is a little extraneous at the moment but prevents the 
    #paginate toggle at the base
    if return_table:
        if 'first_n' in requestDict.keys():
            table = stockTable(filter_object[:int(request.GET['first_n'])])
        else:
            table = stockTable(filter_object)
        return table
    else:
        return filter_object

#In most cases this will be fine, but need to add column
#To seed stock for selected
def newNurseryView(request):
    print("New Nursery view")
    print(request.GET)
    stockFilters = request.GET

    #Pass on dictionary of get request to subsequent trials
    if request.method == 'GET':
        return render(request, "germplasm/nursery_creation.html", { 'stock_filters' : stockFilters} )#, {"form": TrialDetailsForm()})

def newNurseryFormsView(request):
    print("New nursery forms view")
    print(request.GET)
    if request.method == 'GET':
        stockFilters = request.GET
        #I think that this is a reasonable way to do this. 
        return render(request, "germplasm/nursery_creation_forms.html", {'upload_form': UploadStocksForm(), 'stock_filters' : stockFilters})

def newNurseryPlotsTableView(request):
    print("New plots table view")
    print(request.GET)
    baseTable = filterStockTable(request, return_table = False)

    if request.method == 'GET':
        requestDict = request.GET
    elif request.method == 'POST':
        requestDict = request.POST
        print("RECEIVED A POST REQUEST")

    checkKeys = [key for key in requestDict.keys() if re.match(r'^check-entry', key)]
    checkLines = [requestDict[value] for value in checkKeys] 

    tempData = []
    
    starting_plot = int(requestDict['starting-plot']) 

    #inconsistent variable naming format in this view 
    curPlot = starting_plot

    short_year_str = requestDict['nursery-year'][2:4]

    #TD -Calculate total length of nursery to get prepend digits
    if requestDict['plot-type'] == "HRs":

      #Two different modes, fixed number of HRs per stock, or
      #use all available heads. One requires set #
      if requestDict['row-number'] != "Available":
        rowsPerFamily = int(requestDict['row-number'])

      for stock in baseTable:
        if requestDict['row-number'] == "Available":
            rowsPerFamily = int(stock.amount_decimal)

        famRowsAllocated = 0
        while famRowsAllocated < rowsPerFamily:
            curPlotStr = "_" + str(curPlot).rjust(5, "0")

            #Are we in a plot id that checks could be in?
            #Our HR ranges are 50 wide!
            range_pos = (curPlot - starting_plot) % 50
            if range_pos in range(0, len(checkLines)):
                newPlot = {
                    "plot_id" : "WHR" + short_year_str + str(curPlotStr),
                    "trial" : requestDict['nursery-name'],
                    "experiment" : "Experiment",
                    "desig_text" :  checkLines[range_pos],
                    "entry_fixed" : False
                    } 
            else:
                newPlot = {
                    "plot_id" : "WHR" + short_year_str + str(curPlotStr),
                    "source_stock" : stock,
                    "family" : stock.family,
                    "trial" : requestDict['nursery-name'],
                    "experiment" : "Experiment",
                    "desig_text" : stock.source_plot.desig_text + "-" + str(famRowsAllocated + 1),
                    "gen_derived_int" : stock.gen_derived_int , #This is set in *stock* logic
                    "gen_inbred_int" : stock.gen_inbred_int,
                    "entry_fixed" : False
                    } 
                famRowsAllocated += 1

            tempData.append(newPlot)
            curPlot += 1 

    elif requestDict['plot-type'] == "Pots":
      baseTable = baseTable.order_by('family')
      potsPerStock = int(requestDict['pot-number'])
      for stock in baseTable:
        stockPotsAllocated = 0
        while stockPotsAllocated < potsPerStock:
            if potsPerStock > 1:
                new_desig_text = stock.stock_id + "-" + str(stockPotsAllocated + 1)
            else:
                new_desig_text = stock.stock_id

sg_db/germplasm/templates/germplasm/nursery_creation.html
{% extends "base.html" %}  

{% load django_tables2 %}
{% load static %}

{% block extrastyles %}
	<title> Create Nursery </title>
	<link rel="stylesheet" href={% static 'sg_db/css/table_style.css' %}>
{% endblock %}

{% block main %} 

<main>

	<h2> Create Nursery </h2>
	
	<div hx-get="{% url 'germplasm:new_nursery_forms_view' %}" 
	     hx-trigger="load" 
	     hx-vals='{"filter" : "{{ stock_filters.filter }}",
	     	       "gens" : "{{ stock_filters.gens }}",
	     	       "year" : "{{ stock_filters.year }}",
	     	       "sd_units" : "{{ stock_filters.sd_units }}"}'
	     hx-swap="outerHTML">
	          Error loading table!

	</div>

</main>

{% endblock %} 

sg_db/germplasm/templates/germplasm/nursery_creation_forms.html
{# Add htmx code at top level because submits GET with all forms #}
<div  class="table-tools-wrapper">
    <div class = "row">
      <div class = "third-table">
        <div class = "column">
	{#Need to add other filtering params to this #}
	  <div class = "table-fade-wrapper">
	    <div hx-get="{% url 'germplasm:stocks_table_view' %}" 
		 hx-trigger="load" 
		 hx-vals='{"filter" : "{{ stock_filters.filter}}",
			     "gens" : "{{ stock_filters.gens}}",
			     "year" : "{{ stock_filters.year}}",
		             "sd_units" : "{{ stock_filters.sd_units}}",
		             "first_n" : "5"}'
		 hx-swap="outerHTML">
		 Error loading table!
	    </div>
	    <fade/>
	  </div>
	  <div class = "vertical-seperator" style="fontsize: x-large;">
		  &#x25BC;
	  </div>
	  <div class = "table-fade-wrapper">
	    <div class = "new-plots-table">
	    </div>
	    <fade/>
	  </div>
        </div>
      </div>
      <div class = "column">
        <div class = "table-options">	
	      <h3> <span> New Trial: </span> <h3>
	      <form hx-post="{% url 'germplasm:new_nursery_plots_table' %}"
		    hx-include="[name='nursery-name'],
				  [name='nursery-year'],
				  [name='nursery-loc'],
				  [name='plot-type'],
				  [name='starting-plot'],
				  [name='row-number'],
				  [name='pot-number'],
				  [name='check-every'],
		                  [name='check-entry-one'],
		      	          [name='check-entry-two'],
		      	          [name='check-entry-three'],
		      	          [name='check-entry-four'],
		      	          [name='check-entry-five']"
                    hx-vals='{"filter" : "{{ stock_filters.filter}}",
			     "gens" : "{{ stock_filters.gens}}",
			     "year" : "{{ stock_filters.year}}",
		             "sd_units" : "{{ stock_filters.sd_units}}"}'
		    hx-target="div.post-status-message"
		    hx-swap="innerHTML">

	      <label for = "nursery-name"
		     class = "options-box"> Trial name: </label>

              <input id = "nursery-name" name = "nursery-name" type = "text" value = "">
	      <br>
	      <label for = "nursery-year"
		     class = "options-box"> Trial year: </label>

              <input id = "nursery-year" name = "nursery-year" type = "number"
               value = "" min = "2023" max = "2099">
	      <br>
	      <label for = "nursery-loc"
		     class = "options-box"> Trial loc: </label>

              <input id = "nursery-loc" name = "nursery-loc" type = "text" value = "">
	      <br>

	      <label for = "plot-type"
		     class = "options-box"> Trial type: </label>


	      <select id = "plot-type" name = "plot-type" class = "select-options-box" 
		      hx-get = "{% url 'germplasm:new_nursery_details' %}" 
		      hx-trigger="load, click changed" 
		      hx-swap="outerHTML" 
		      hx-target="div.nursery-details">
		      <option value = "HRs">Headrows</option>
		      <option value = "Pots">Pots</option>
		      <option value = "Yield">Yield plots</option>
		      <option value = "SP">Single plants</option>
	      </select>


	      <h3> <span> Nursery Options: </span> <h3>

	      <br/>
	      <label for = "starting-plot"
		     class = "options-box"> Starting plot: </label>
	      <input id = "starting-plot" name = "starting-plot",
	      	     class = "options-box", type = "text", value = "1"> 
	      <br/>
      	      <div class = "nursery-details"> 
	        <p> Nursery Details </p>
              </div>

	      <input type = "submit", value = "Generate">
	      </form>

	      <div class="post-status-message"> <p> Nursery not submitted. </p> 
	      </div>

	      <div class = "background-table-regenerate"
		      hx-get="{% url 'germplasm:new_nursery_plots_table' %}"
		      hx-trigger="every 200ms"
		      hx-target="div.new-plots-table"
		      hx-include="[name='nursery-name'],
				  [name='nursery-year'],
				  [name='nursery-loc'],
				  [name='plot-type'],
				  [name='starting-plot'],
				  [name='row-number'],
				  [name='pot-number'],
				  [name='check-every'],
		                  [name='check-entry-one'],
		      	          [name='check-entry-two'],
		      	          [name='check-entry-three'],
		      	          [name='check-entry-four'],
		      	          [name='check-entry-five']"
                      hx-vals='{"filter" : "{{ stock_filters.filter }}",
			     "gens" : "{{ stock_filters.gens }}",
			     "year" : "{{ stock_filters.year }}",
		             "sd_units" : "{{ stock_filters.sd_units }}"}'
		      hx-swap="innerHTML">
	      </div>
        </div>
      </div>
    </div>
</div>

sg_db/germplasm/templates/germplasm/plots_index.html
{% extends "base.html" %}  

{% load django_tables2 %}
{% load static %}

{% block extrastyles %}
	<title> Wheat plots </title>
	<link rel="stylesheet" href={% static 'sg_db/css/table_style.css' %}>
{% endblock %}

{% block main %} 

<main>

	<h2> Plots </h2>

	<div hx-get="{% url 'germplasm:plots_wrapper_view' %}"
	     hx-trigger="load"
	     hx-swap="outerHTML">
		Error loading table wrapper!
	</div>

</main>

{% endblock %} 

sg_db/germplasm/templates/germplasm/plots_table_wrapper.html
<div class="table-tools-wrapper">


	<label for = "filter-box"
	       class = "filter-box"> Search table: </label>
	<input type = "search"
	       class = "filter-box"
	       name = "filter"
	       id = "filter-box"
	       placeholder = "Filter..."
	       hx-get="{% url 'germplasm:plots_table_view' %}"
	       hx-trigger="keyup delay:500ms, changed, search"
	       hx-target="div.table-container"
	       hx-swap="outerHTML">

	<div hx-get="{% url 'germplasm:plots_table_view' %}" hx-trigger="load" hx-swap="outerHTML">
		Error loading table!
	</div>

	<form style="display: inline" 
	      action="/germplasm/plotsUpload" 
	      method="get">
		<button>Manual Upload</button>
	</form>

	<form style="display: inline" 
	      hx-trigger="click"
	      hx-get="{% url 'tools:htmx_csv_view' %}"
	      hx-vals='{ "requested_model" : "Plots" }'
	      hx-include="[name='filter']"
	      >
		<button>Download CSV</button>
	</form>

</div>

sg_db/germplasm/templates/germplasm/predictions_index.html
{% extends "base.html" %}  

{% load django_tables2 %}
{% load static %}

{% block extrastyles %}
	<title> Predictions by Trial </title>
	<link rel="stylesheet" href={% static 'sg_db/css/table_style.css' %}>
{% endblock %}

{% block main %} 

<main>

	<h2> Predictions by Trial </h2>

	<div hx-get="{% url 'germplasm:predictions_wrapper_view' %}"
	     hx-trigger="load"
	     hx-swap="outerHTML">
		Error loading table wrapper!
	</div>

</main>

{% endblock %} 

sg_db/germplasm/templates/germplasm/stocks_table_wrapper.html
{# Add htmx code at top level because submits GET with all forms #}
<div  class="table-tools-wrapper">

    <div class = "row">
      <div class = "column">
	<div class = "half-table">
	  <div hx-get="{% url 'germplasm:stocks_table_view' %}" 
		  hx-trigger="load" 
		  hx-swap="outerHTML"
		  hx-vals='{"n-rows" : "5"}'>
		  Error loading table!
	  </div>
	</div>
      </div>
      <div class = "column">
	<div class = "table-options">
	<h2> Generate Trial from Stocks </h2>
	<form id="form" method="GET" action="{% url 'germplasm:new_nursery_view' %}">
	  <label for = "filter-options-box"
	         class = "options-box"> Search stocks: </label>
	  <input type = "search"
	       class = "filter-options-box"
	       name = "filter"
	       id = "filter-options-box"
	       placeholder = "Filter...">
	  </br>
	  <label for = "filter-box"
	         class = "options-box"> Stock gen: </label>
	  <select id="gens" name="gens" class = "select-options-box">
	    <option value = "">All</option>
	    <option value = "F1">F1</option>
	    <option value = "F2">F2</option>
	    <option value = "F3">F3</option>
	    <option value = "F4">F4</option>
	    <option value = "F5">F5</option>
	  </select>
	  <br/>
	   {# NEed to default and auto-generate #} 
	  <label for = "year"
	         class = "options-box"> Year: </label>
	    <select id="year" name = "year" class = "select-options-box">
	      <option value = "">All</option>
	      <option value = "2020">2020</option>
	      <option value = "2021">2021</option>
	      <option value = "2022">2022</option>
	      <option value = "2023">2023</option>
	      <option value = "2024">2024</option>
	      <option value = "2025">2025</option>
	      <option value = "2026">2026</option>
	    </select>
	  <br/>
	  <label for = "sd_units"
	         class = "options-box"> Stock type: </label>
	  <select id="sd_units" name = "sd_units" class = "select-options-box">
            <option value = ""> All </option>
            <option value = "sds"> Seeds </option>
            <option value = "hds"> Heads </option>
            <option value = "g"> Grams </option>
            <option value = "lb"> Pounds </option>
	  </select>
	  <br/>
	  <button hx-get="{% url 'germplasm:stocks_table_view' %}"
		  hx-include="[name='filter'], [name='gens'], 
	              	       [name='year'], [name='sd_units']"
	          hx-trigger="click"
	          hx-target="div.table-container"
	          hx-swap="outerHTML">
		  Update Table </button>
	  <br/>
            <input type="submit" value = "submit">
          </form>
	  
        <form style="display: inline"
              hx-trigger="click"
              hx-get="{% url 'tools:htmx_csv_view' %}"
              hx-vals='{ "requested_model" : "Stocks" }'
	      hx-include="[name='filter']"
              >
                <button>Download CSV</button>
        </form>
	  <br/>


	  <h2> Upload New Stocks </h2>

          <form hx-post = "{% url 'germplasm:stocks_wrapper_view' %}"
	      hx-include="[name='sd_units']"
              hx-encoding = "multipart/form-data"
              hx-target="div.table-tools-wrapper">
                {% csrf_token %}
                {{ upload_form }}
		<select name="sd_units_upload" id="sd_units_upload">
			<option value="hds">Heads</option>
			<option value="g">Grams</option>
			<option value="lb">Pounds</option>
			<option value="sds">Seeds</option>
		</select>
		<br/>
                <input class = "button" type="submit" value = "Upload">
          </form>
	</div>
      </div>
    </div>


</div>

sg_db/germplasm/templates/germplasm/trialDetail.html
<div class="table-tools-wrapper">
  <div class="entry-title">
	<h3> <span> {{ entry.trial_id }}</span></h3>
  </div>
  <div class="row">
    <div class="column">
      <div class="detail-box">
	<h3> Year: </h3>
	<p class="detail_info"> {{entry.year_text}} </p>
      </div>
      <div class="detail-box">
	<h3> Location: </h3>
	<p class="detail_info"> {{entry.location_text}} </p>
      </div>
      <div class="detail-box">
	<h3> Trial type: </h3>
	<p class="detail_info"> {{entry.plot_type}} </p>
      </div>
      <div class="detail-box">
	<h3> Notes: </h3>
	<p class="detail_info"> {{entry.notes_text}} </p>
      </div>
    </div>
    <div class="column">
      <div class="detail-box">
	<h3> Planting Date </h3>
	<p class="detail_info"> {{entry.planting_date}} </p>
      </div>
      <div class="detail-box">
	<h3> Harvest Date </h3>
	<p class="detail_info"> {{entry.harvest_date}} </p>
      </div>
      <div class="detail-box">
	<h3> Status  </h3>
	<p class="detail_info"> {{entry.status_text}} </p>
      </div>
    </div>
  </div>
	<br / >

        <div hx-get="{% url 'germplasm:predictions_table_view' trial_filter=entry.trial_id %}" hx-trigger="load" hx-swap="outerHTML">
                No predictions found for trial!
        </div>

	<button hx-get="{% url 'germplasm:trials_wrapper_view' %}"
		hx-target="div.table-tools-wrapper"
		hx-swap="outerHTML">Return</button>

	<button hx-get="{% url 'crossing:entry_edit_form' entry.pk  %}"
		hx-target="div.table-tools-wrapper"
		> Edit </button>


	<button hx-post="{% url 'tools:fieldbooks_view'  %}"
		hx-target="body"
		hx-include="[name='select_run']"
		hx-vals='{"trial_str" : "{{ entry.trial_id }}"
		}'
		> Generate Fieldbook </button>
 </div>