sg_db/sg_db/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="sg_db/index_info.html"), name = "index_info"), #Allows loading template directly without views file
    path("crossing_shiny", TemplateView.as_view(template_name="sg_db/crossing_shiny.html"), name = "crossing_shiny"), 
    path("crossesmade_shiny", TemplateView.as_view(template_name="sg_db/crossesmade_shiny.html"), name = "crossesmade_shiny"), 
    path('crossing/', include("crossing.urls")),
    path('tools/', include("tools.urls")),
    path('germplasm/', include("germplasm.urls")),
    path('admin/', admin.site.urls),
]

sg_db/tools/urls.py
from django.urls import path

from . import views


app_name = "tools"
urlpatterns = [
       # path("", #Index view maybe?
       path('labels', views.lblView, name = "labels_view"),
       path('labels/display', views.labelDisplayView, name = "display_label_view"),
       path('fieldbooks', views.fieldbookView, name = "fieldbooks_view"),
       path('fieldbooks/<str:file_str>', views.renderFieldbookView, name = 'render_fieldbook_view'),
       path('export/csv/<str:requested_model>', views.export_csv, name='export_csv'),
       path('export/csv/<str:requested_model>/<str:filter_str>', views.export_csv, name='export_csv'),
       path('export/htmx', views.htmx_csv_view, name = "htmx_csv_view"),
       #path('export/lbl/<str:requested_model>', views.export_labels, name='export_labels'),
       ]

sg_db/tools/models.py
from django.db import models

# Create your models here.

sg_db/tools/forms.py
from django.forms import IntegerField, FileField, BooleanField, DateField, Form, ModelForm, NumberInput, SelectDateWidget



class UploadLabelsForm(Form):
    Labels_File = FileField()
    Labels_File.widget.attrs.update({'class': 'file-upload'})

    Times_To_Print = IntegerField(label = 'Times to print', initial = '1')
    Times_To_Print.widget.attrs.update({'class': 'times-counter',
                                        'style': 'width:10ch',
                                        'max': '99',
                                        'min': '1'})

    Include_Barcode = BooleanField(label = "Include Barcode?", initial = True, required = False)
    Include_Barcode.widget.attrs.update({'class': 'check-box'})

    Date_Str = DateField(label = "Date", widget = SelectDateWidget(empty_label="Nothing"))


#I believe this is only called by WCP_Entries view
class TimesToPrintForm(Form):
    Times_To_Print = IntegerField(label = 'Entry List Labels: ', initial = '1')
    Times_To_Print.widget.attrs.update({'style': 'width:5ch',
                                        'class': 'times-counter',
                                        'max': '99',
                                        'min': '1'})

sg_db/tools/views.py
import csv
import os
import re
import requests
import shutil

from datetime import date, datetime
from io import TextIOWrapper
from pathlib import Path
from math import ceil

from django.shortcuts import get_object_or_404, render
from django.db.models import Q, Min, Max
from django.conf import settings
from django.template.loader import render_to_string

from django.http import HttpResponse

from .forms import UploadLabelsForm
from .tables import FamilyPlotsTable

from crossing.models import WCP_Entries, Crosses, Families
from germplasm.models import Plots, Stocks, Trials, Predictions

def lblView(request):
    if request.method == 'GET':
        return render(request, "tools/labels.html", {"label_form": UploadLabelsForm()}) #Merge?
    elif request.method == 'POST':
        #Bool field not included in post unless True
        if 'Include_Barcode' in request.POST.keys():
            include_barcode_bool = True
        else:
            include_barcode_bool = False

        times_to_print_int = int(request.POST['Times_To_Print'])
        
        Labels_File = request.FILES["Labels_File"]
        rows = TextIOWrapper(Labels_File, encoding="utf-8", newline="")
        row_list = []
        for row in csv.DictReader(rows):
           row_list.append(row)

        return(export_labels(request, "CSV", include_barcode = include_barcode_bool, times_to_print = times_to_print_int, csv_file = row_list))

#Generate PNG of label string based on labelry API
def labelDisplayView(request):
    if 'Include_Barcode' in request.POST.keys():
        include_barcode_bool = True
    else:
        include_barcode_bool = False

    times_to_print_int = int(request.POST['Times_To_Print'])
        
    Labels_File = request.FILES["Labels_File"]
    rows = TextIOWrapper(Labels_File, encoding="utf-8", newline="")
    
    requested_model = "CSV" 

    first_row = next(csv.DictReader(rows))

    zpl_str = export_labels(request, requested_model, include_barcode = include_barcode_bool,
                  include_date = True, times_to_print = times_to_print_int, 
                  csv_file = first_row, sample_first_entry = True)
    zpl_str = re.sub("\n", "", zpl_str)

    #Have to create unique file names to avoid static cache
    labl_date_string = str(datetime.now())

    lbl_path_folder = "/var/www/sg_db/static/tools/media/"
    lbl_file_name = "display_lbl" + labl_date_string + ".png"

    lbl_path = lbl_path_folder + lbl_file_name

    #Delete files if present. But I only want to do it *after* refresh.
    #Path(lbl_path).unlink(missing_ok=True)
    for file in Path(lbl_path_folder).glob("display_lbl*.png"):
        file.unlink()

    lbl_files = {'file' : zpl_str}
    #Can modify label size here
    lbl_url = 'http://api.labelary.com/v1/printers/8dpmm/labels/2.5x1/0/'
    lbl_response = requests.post(lbl_url, files = lbl_files, stream = True)

    if lbl_response.status_code == 200:
        lbl_response.raw.decode_content = True
        with open(lbl_path, 'wb') as out_file:
            shutil.copyfileobj(lbl_response.raw, out_file)
        

        return render(request, "tools/partials/label_display.html", {"label_png" : "tools/media/" + lbl_file_name})
    else:
        print('Error: ' + lbl_response.text)


def export_labels(request, requested_model, second_row_text = "", include_barcode = True,
                  include_date = True, times_to_print = 1, csv_file = None, sample_first_entry = False):

    response = HttpResponse(content_type = 'text/plain')

    if requested_model == "WCP_Entries":
        cur_model = WCP_Entries
    elif requested_model == "Crosses":
        cur_model = Crosses

    file_date_string = date.today().strftime("%b%d%y")
    labl_date_string = date.today().strftime("%m/%d/%Y")

    file_name = requested_model + "_lbls_" + file_date_string + ".zpl"
    response['Content-Disposition'] = 'attachment; filename="' + file_name +  '"'

    if requested_model != "CSV":
        row_items = cur_model.objects.all().values_list("wcp_id", "desig_text", "cp_group_text")
    else:
        row_items = csv_file

    if sample_first_entry == True:
        row_item = [row_items['id'], row_items['row_1'], row_items['row_2']]
        new_zpl_str = get_zpl_str(row_item, requested_model = requested_model,
                second_row_text = second_row_text, labl_date_string = labl_date_string, include_barcode = include_barcode)
        return new_zpl_str

    else:
        for row_item in row_items:
          if requested_model == "CSV":
              row_item = [row_item['id'], row_item['row_1'], row_item['row_2']]
              second_row_text = ""
          elif requested_model == "WCP_Entries":
              second_row_text = "Group"
          else:
              second_row_text = ""

          for _ in range(times_to_print):
              new_zpl_str = get_zpl_str(row_item, requested_model = requested_model, 
                      second_row_text = second_row_text, labl_date_string = labl_date_string, include_barcode = include_barcode)
              response.write(new_zpl_str)

        return response

def get_zpl_str(row_item, requested_model, second_row_text = "", labl_date_string = "", include_barcode = False):
    new_zpl_str = ""
    new_zpl_str += "^XA\n"
    new_zpl_str += "^CF0,40\n"
    new_zpl_str += "^FO10,5^GB490,3,3^FS\n"
    if requested_model in ["WCP_Entries", "CSV"]:
       new_zpl_str += "^FO15,35^FD" + row_item[0] + "^FS\n"
       new_zpl_str += "^CF0,20\n"
       new_zpl_str += "^FO16,90^FD" + row_item[1] + "^FS\n"
       new_zpl_str += "^FO16,125^FD" + second_row_text + row_item[2] + "^FS\n"
       if labl_date_string != "":
            new_zpl_str += "^FO16,160^FD" + labl_date_string + "^FS\n"
       if include_barcode == True:
            new_zpl_str += "^FO320,20^BQN,2,7,Q,7^FDQA," + row_item[0] + "^FS\n"
    new_zpl_str += "^FO10, 195^GB490,3,3^FS\n"
    new_zpl_str += "^XZ\n"

    return(new_zpl_str)

#Because htmx just does ajax requests, to do a CSV download have to redirect
def htmx_csv_view(request):
    requested_model = request.GET["requested_model"]
    filter_str = request.GET["filter"]

    #If filter box is empty
    if filter_str == "":
        csv_url = "/tools/export/csv/" + requested_model
    else:
        csv_url = "/tools/export/csv/" + requested_model + "/" + filter_str

    response = HttpResponse()
    response["HX-Redirect"] = csv_url

    return(response)

def export_csv(request, requested_model, filter_str = ""):
    response = HttpResponse(content_type='text/csv')

    if requested_model == "WCP_Entries":
            cur_model = WCP_Entries
    elif requested_model == "Crosses":
            cur_model = Crosses
    elif requested_model == "Families":
            cur_model = Families
    elif requested_model == "Plots":
            cur_model = Plots 
    elif requested_model == "Stocks":
            cur_model = Stocks 
    elif requested_model == "Trials":
            cur_model = Trials


    date_string = date.today().strftime("%b%d%y")
    file_name = requested_model + "_" + date_string + ".csv"
    response['Content-Disposition'] = 'attachment; filename="' + file_name +  '"'

    writer = csv.writer(response)

    #Gets names of all model fields -- probably better way to do this...
    field_list = []
    for field in cur_model._meta.get_fields():
        if field.concrete == True:
            field_list.append(field.name)

    print(field_list)

    writer.writerow(field_list)

    #The issue here is with get_fields getting fields from the plot instead of cross.. no idea why.
    print(filter_str)
    if filter_str != "":
        filter_object = cur_model.objects.all()
        if requested_model == "Stocks": 
            sel_rows = filter_object.filter(Q(stock_id__icontains=filter_str))
        elif requested_model == "Plots": 
            sel_rows = filter_object.filter(Q(plot_id__icontains=filter_str) | Q(trial__trial_id__icontains=filter_str))
        row_items = sel_rows.values_list(*field_list)
    else:
        row_items = cur_model.objects.all().values_list(*field_list)
            
    for row_item in row_items:
        writer.writerow(row_item)

    return response

def getScaleColor(value, max_val, min_val):
    scale_pos = ["#ffffe0", "#ebeed3", "#bec8b5", "#83948a", "#395653", "#003233"]
    scale_neg = ["#ffffe0", "#f3eccc", "#d8bfa0", "#b48166", "#803522", "#580000"]

    #I'm assuming max is not negative.
    if value >= 0:
        scaled_value = value / max_val
        scaled_index = int(round(scaled_value * 5, 0))
        hex_val = scale_pos[scaled_index]
    else:
        #Maintains negative value
        scaled_value = value / min_val
        scaled_index = int(round(scaled_value * 5, 0))
        hex_val = scale_neg[scaled_index]

    return hex_val

def getFieldbookArgs(trial_family_transitions, preds_dict, max_min_dict, trial_str, cut_str):
    args = {}
    args['preds'] = {}

    #Iterate through plots to find the transition points between families and plots. All available plots will be queried at once, and filtered to remove extraneous ones..
    #We store the previous plot so we can filter by a range
    prev_plt_str = None

    #The first will get skipped, which is okay if we start with a 001, but if we start with an 002 it omits the 001.
    #This is an easy way to get the 001. If you're not an 002 something's wrong! 
    if re.search("\d$", trial_family_transitions[0][0]).group(0) == "2":
        first_plt_str = trial_family_transitions[0][0]
        prev_plt_str = first_plt_str[:-1] + "1"

    for plot_family in trial_family_transitions:
        plt_str = plot_family[0]
        fam_str = plot_family[1]

        #Prepare info for family details and predictions
        try:
            fam_object = Families.objects.get(pk = fam_str)
        except:
            if not fam_str is None:
                print("Error -- family " + str(fam_str) + " not found.")
                fam_str = None

        if not fam_str is None:

sg_db/tools/templates/tools/fieldbook_filedir.html
{% load static %}

{% block extrastyles %}
	<title> Headrow Fieldbooks </title>
	<link rel="stylesheet" href={% static 'sg_db/css/fieldbook_style.css' %}>
{% endblock %}

{% block main %}


<div class="fieldbook">
<main>
  <ul>
  {% for file_str in fieldbook_files %}
  	<li><a href="{% url 'tools:render_fieldbook_view' file_str %}">
		{{ file_str }}
		</a></li>
  {% endfor %}
  </ul>
</main>
</div>

{% endblock %}

sg_db/tools/templates/tools/fieldbooks.html
{% load static %}

{% block extrastyles %}
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title> {{ trial_info.trial_str }} Fieldbook </title>
	<link rel="stylesheet" href={% static 'sg_db/css/base_style.css' %}>
        <link rel="stylesheet" href={% static 'sg_db/css/table_style.css' %}>
	<link rel="stylesheet" href={% static 'sg_db/css/fieldbook_style.css' %}>
{% endblock %}

{% block main %}


<div class="fieldbook">
<main>
  <div class="title-page">
	<h1> {{ trial_info.trial_str }} </h1>
	<h1 style="font-size:18px;"> Generated Fieldbook </h1>
	<h1 style="font-size:18px;color:red;"> DRAFT FORMATTING </h1>

	<div class="outer-container-title">
        <div class="title-column">
	<h2> Trial Details: </h2>
	<div class="trial-info">
        <div class="detail-box">
	  <h3> Year: <span style="font-style:italic;"> {{ trial_info.trial_year}} </span> </h3>
        </div>
        <div class="detail-box">
          <h3> Location: <span style="font-style:italic;">{{ trial_info.trial_loc}} </span></h3>
        </div>
        <div class="detail-box">
	  <h3> Trial type: <span style="font-style:italic;">{{ trial_info.trial_type }} </span> </h3>
	</div>
	</div>
	</div>
	<div class="title-column">
	<h2> Predicted Phenotypes: </h2>

	{% for run, pheno in trial_info.fb_preds.items %}
        <div class="detail-box">
	        <h3> {{ pheno }} : <span style="font-size:14px;font-style:italic;"> {{ run }} </span> </h3>
        </div>
	{% endfor %}
	</div>
	</div>

	<div class="main_image">
	        <img src="{% static 'sg_db/media/headrows.jpeg' %}" alt="headrows_image" style="width:600px;height:452px;border:6px solid #555;">
	</div>

        <div class="detail-box">
	        <p> Noah DeWitt / NDeWitt@agcenter.lsu.edu / (352)-293-5437 </p>
	        <p> Stephen Harrison / SHarrison@agcenter.lsu.edu / (225)-281-9446 </p>
	</div>
  </div>


	      {% for family, preds in preds.items %}
		{% if "_" in preds.family_object %}
	        	{% include 'tools/partials/familyDetail_partial_check.html' %}
		{% else %}
	        	{% include 'tools/partials/familyDetail_partial.html' %}
	        	{% include 'tools/partials/familyPreds_partial.html' %}
		{% endif %}
	        {% include 'tools/partials/family_plots_table.html' %}
	      {% endfor %}

</main>
</div>

{% endblock %}

sg_db/tools/templates/tools/labels.html
<!DOCTYPE html>
{% extends "base.html" %}  

{% load static %}

{% block extrastyles %}

<title> Label Generator </title>

{% endblock %}

{% block main %} 

<main>
    <h2> Generate Labels </h2>

    <div class = "row">
      <div class = "column">
	<form id = "label-generation-form" 
	    action="/tools/labels"
	    enctype="multipart/form-data"
	    method="post">
	    {% csrf_token %}
	    {% for field in label_form %} 
	      <div class = "child-row">
		<div class = "child-row-container">
		  {% if forloop.counter != 1 %}
	    	    <label class = "options-box"> {{field.label_tag}} </label>		
		  {% endif %}
		  {{ field }} 
		</div>
	      </div>

	    {% endfor %}
	    <button hx-post = "{% url 'tools:display_label_view' %}"
		    hx-encoding='multipart/form-data'
	     	    hx-trigger = "click"
	     	    hx-target = "div.display_label_wrapper"
		    hx-swap = "outerHTML"> Update </button>

	    <input type="submit" 
		   class='button'
	           name = 'upload_files' 
		   value = "Download">
	</form>
      </div>
      <div class = "column">
	<div class = "display_label_wrapper">
		<div class = "display_label">
			<img src = "{% static 'tools/media/blank_lbl.png' %}">
		</div>

	</div>
    </div>
</main>

{% endblock %} 